name: marine-processing-test

channels:
    - conda-forge
    - nodefaults

dependencies:
    # for testing
    - pytest
    - pytest-cov
    - pytest-env
    - pip:
      - cdm_reader_mapper
      - pandas-validation
      - simplejson
